### PR TITLE
Add option to disable blank searches

### PR DESCRIPTION
**Pull request by rakeshbala**
This pull request adds an option to disable blank searches. Current behaviour runs blank search against the word under the cursor. Setting the 'g:ack_no_blank_search' changes this behaviour to echo an error message and return.

It also bypasses search through the ack package if the cursor is under empty string

### CODE REVIEW

**Comment by ches** [comment]
Hi @zeroGMac, thanks for cooking this up. My only feedback is that I'd like to change the option name, I think it's awkward to have a negatory option name which you set to a true value to disable a feature, if that makes sense… So it's a slightly wordy, but I'd propose `g:ack_use_cword_for_empty_search` as the option, with default value of `1`.

Could you make that change? Nice idea to no-op if `<cword>` turns out to be empty, by the way.

For posterity this enhancement references #178.

**Comment by ches** [comment]
Please squash the rename into the first commit! 😄

**Comment by zeroGMac** [comment]
Done.

**Comment by ches** [comment]
Sorry for the git gymnastics headache, but it looks like somehow an earlier commit that's already merged snuck into this branch now with a SHA change—could you try to iron that out? Then we're good to go.

**Comment by zeroGMac** [comment]
@ches: I'm not sure how that happened and how to fix that. Any pointers?

**Comment by rakeshbala** [comment]
Done

**Comment by ches** [comment]
Thank you!

**Pull request merged**
