### PR TITLE
g:ackdefaultdir option

### PR DESCRIPTION
**Pull request by lucapette**
I added this option because I don't like the idea of typing in the root of a project at every search. I find that Ack.vim is particularly useful when I can do project-searches. To be honest, I don't know if this is a good way of implementing it. It's working fine with me at the moment and I have done a pull-request just for sharing the idea. If you like it, I can do another commit with docs.

Thank you for the plugin!

### CODE REVIEW

**Comment by gdw2** [comment]
I agree with @vvzz .  I'm an `autochdir` user and also like how CtrlP determines the root path.

**Comment by noscripter** [comment]
+1 for this merge

**Comment by noscripter** [comment]
@lucapette maybe you should also give the default example of setting this option to the root of git or svn project root directory.

**Comment by ches** [comment]
@noscripter See #188 for my recent perspective on basically this same idea. There are a number of ways to skin this cat and I'm not convinced it's within the scope of the search plugin to solve it. Projectionist's `:ProjectDo` is likely a good option if you use that plugin.

One possibility is a variable convention like the one in this proposal, expanded by your own mapping or abbreviation that invokes an `:Ack` command with the path filled. Personally I would do this with a buffer-local variable and set that variable as desired via something like [localvimrc][1] for each project where I want it, or try to detect a `.git` if that's your use case (a global `g:` var is not the appropriate scope for this IMO, I might work on multiple "projects" within one Vim instance and twiddling a single global var then becomes a mess). This should be entirely doable by the user without the plugin needing any specific support for it, such is the beauty of Vim's scriptability.

I can understand how this could be helpful for `'autochdir'` users, however (though some may want/expect exactly the opposite: for `ack.vim` to respect `'autochdir'` just like `:grep` does…). If anyone cooks up a solution like this I'd be glad to include it as a recipe in documentation. If it turns out to be clean and simple enough I might consider including it, but I don't want something as complicated as CtrlP's configuration approach.

[1]: https://github.com/embear/vim-localvimrc

**Pull request closed without merging**
